// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdbPgzCuszF9Xv6RFyuYAZEhmBF4LiWD4',
    appId: '1:185414925403:web:2a43939f51d25ef82a137e',
    messagingSenderId: '185414925403',
    projectId: 'mlkitdemo-a75f2',
    authDomain: 'mlkitdemo-a75f2.firebaseapp.com',
    storageBucket: 'mlkitdemo-a75f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp2gUYsU37KWi0es-2MDB2qcWz5Nc3aOI',
    appId: '1:185414925403:android:020eb2e27e8d9c692a137e',
    messagingSenderId: '185414925403',
    projectId: 'mlkitdemo-a75f2',
    storageBucket: 'mlkitdemo-a75f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvkVlSh5y4-9fCRXFpVYaLFhUBtF7wI8w',
    appId: '1:185414925403:ios:546afc4f80c04adb2a137e',
    messagingSenderId: '185414925403',
    projectId: 'mlkitdemo-a75f2',
    storageBucket: 'mlkitdemo-a75f2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvkVlSh5y4-9fCRXFpVYaLFhUBtF7wI8w',
    appId: '1:185414925403:ios:ea99c12152d20f042a137e',
    messagingSenderId: '185414925403',
    projectId: 'mlkitdemo-a75f2',
    storageBucket: 'mlkitdemo-a75f2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
